services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - uc-network
    restart: always

  backend:
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx512m"
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  frontend:
    environment:
      NEXT_PUBLIC_API_URL: "https://dev.unicloud.projektstudencki.pl/api"

volumes:
  caddy_data:
  caddy_config:

networks:
  uc-network:
    external: true