services:
  backend:
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx512m"
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  frontend:
    environment:
      NEXT_PUBLIC_API_URL: "https://dev.unicloud.projektstudencki.pl/api"

networks:
  uc-network:
    external: true