services:
  uc-backend:
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx512m"
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      ORIGIN: ${ORIGIN}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}
      DEFAULT_STUDENT_PASSWORD: ${DEFAULT_STUDENT_PASSWORD}
      DEFAULT_LECTURER_PASSWORD: ${DEFAULT_LECTURER_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      ADAPTER_AWS_HOST: ${ADAPTER_AWS_HOST}

networks:
  uc-network: